name: Build Gitbook

on:
  push:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    #- uses: actions/setup-node@v2
    #  with:
    #    node-version: '10.15'
    #- run: npm install gitbook-cli -g
    #- run: gitbook fetch 3.2.3
    #- run: gitbook install
    #- run: gitbook build . public
    - name: Gitbook Action           # https://github.com/ZanderZhao/gitbook-action/releases
      uses: ZanderZhao/gitbook-action@v1.2.4  # -> or ZanderZhao/gitbook-action@master.  If not use master click above, use latest please 
      with:                                   #    or fork this repo and use YourName/gitbook-action@master
        token: ${{ secrets.PERSONAL }}
        source_branch: main
